# Generated by Django 2.2.6 on 2019-10-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolgs',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
